export const ACTION_TYPES = {
  GET_USERS: "GET_USERS",
  SET_USER: "SET_USER",
  SAVE_USER_ROLE: "SAVE_USER_ROLE",
  DELETE_USER: "DELETE_USER",
  LOGOUT: "LOGOUT",
  GET_POSTS: "GET_POSTS",
  EDIT_POST: "EDIT_POST",
  SET_POST: "SET_POST",
  RESET_POST: "RESET_POST",
  DELETE_POST: "DELETE_POST",
  ADD_COMMENT: "ADD_COMMENT",
  DELETE_COMMENT: "DELETE_COMMENT",
};
