export const ACTION_TYPES = {
  GET_USERS: "GET_USERS",
  SET_USER: "SET_USER",
  SAVE_USER_ROLE: "SAVE_USER_ROLE",
  DELETE_USER: "DELETE_USER",
  LOGOUT: "LOGOUT",
  GET_BIDS: "GET_BIDS",
  EDIT_BID: "EDIT_BID",
  SET_BID: "SET_BID",
  RESET_BID: "RESET_BID",
  DELETE_BID: "DELETE_BID",
  ADD_COMMENT: "ADD_COMMENT",
  DELETE_COMMENT: "DELETE_COMMENT",
};
